export interface EvidenceSpan { segment_id:string; start_ms:number; end_ms:number }
export interface TrustedSegment { id:string; start_ms:number; end_ms:number; text:string; raw_speaker_label:string; speaker_id?:string|null; revision:number }
export interface TrustedClaim { id:string; type:string; text:string; status:string; version:number; evidence:EvidenceSpan[] }
export interface TrustedRecord { meeting:{id:string;title:string;mode:string}; transcript_version:number; segments:TrustedSegment[]; claims:TrustedClaim[]; snapshot:null|{id:string;version:number;sha256:string}; }
export class TrustedConflictError extends Error { constructor(public currentVersion:number, public detail:unknown){super('VERSION_CONFLICT')} }
async function trustedRequest<T>(path:string,init:RequestInit={}):Promise<T>{const token=sessionStorage.getItem('workspace_token');const response=await fetch(`/api/v1/trusted${path}`,{...init,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{ }),...(init.headers??{})}});const body=await response.json().catch(()=>({}));if(response.status===409&&body?.detail?.code==='VERSION_CONFLICT')throw new TrustedConflictError(body.detail.current_version,body.detail);if(!response.ok)throw new Error(typeof body.detail==='string'?body.detail:JSON.stringify(body.detail??'Request failed'));return body as T}
export const getTrustedRecord=(id:string)=>trustedRequest<TrustedRecord>(`/meetings/${id}/record`);
export const updateTrustedClaim=(meetingId:string,claimId:string,version:number,text:string,evidence:EvidenceSpan[])=>trustedRequest<{id:string;version:number;status:string}>(`/meetings/${meetingId}/claims/${claimId}`,{method:'PUT',headers:{'If-Match':String(version)},body:JSON.stringify({text,evidence})});
export const decideTrustedClaim=(meetingId:string,claimId:string,decision:'approve'|'reject',reason?:string)=>trustedRequest(`/meetings/${meetingId}/claims/${claimId}/decisions`,{method:'POST',body:JSON.stringify({decision,reason})});
export const mapTrustedSpeaker=(meetingId:string,body:{raw_label:string;canonical_name:string;user_id?:string|null;segment_ids:string[];expected_transcript_version:number})=>trustedRequest<{mapping_id:string;transcript_version:number;impacted_claim_ids:string[]}>(`/meetings/${meetingId}/speaker-mappings`,{method:'POST',body:JSON.stringify(body)});
export const publishTrustedRecord=(id:string)=>trustedRequest<{snapshot_id:string;version:number;sha256:string}>(`/meetings/${id}/publish`,{method:'POST'});
