import { useEffect,useState } from 'react';
import { workspaceRequest } from '../api/workspace';
import { governanceRequest } from '../api/governance';
interface Control{target?:string;id:string;level:string;title:string;detail:string;evidence:string;last_checked:string;owner:string;remediation:string}
type Tab='overview'|'audit'|'policies';
export function ComplianceCenter(){
 const[tab,setTab]=useState<Tab>('overview');const[controls,setControls]=useState<Control[]>([]);const[audit,setAudit]=useState<Array<{id:string;event:string;at:string}>>([]);const[error,setError]=useState('');const[team,setTeam]=useState('');const[busy,setBusy]=useState(false);const[success,setSuccess]=useState('');const[policy,setPolicy]=useState({version:0,providers:{allowed_providers:['openai','local'],prohibit_fallback:true}});
 useEffect(()=>{void workspaceRequest<{controls:Control[];audit:Array<{id:string;event:string;at:string}>}>('/compliance').then(b=>{setControls(b.controls);setAudit(b.audit)}).catch((e:Error)=>setError(e.message))},[]);
 const loadPolicy=async()=>{if(!team){setError('Enter a workspace team ID.');return}setBusy(true);setError('');try{const p=await governanceRequest<typeof policy&{team_id:string}>(`/policies/current?team_id=${encodeURIComponent(team)}`);setPolicy(p);setSuccess(`Policy version ${p.version} loaded.`)}catch(e){setError(e instanceof Error?e.message:'Policy could not be loaded.')}finally{setBusy(false)}};
 const exportAudit=async()=>{if(!team){setError('Enter a workspace team ID.');return}setBusy(true);setError('');try{const response=await fetch('/api/v1/governance/audit/exports',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('meetingnotes_token')??localStorage.getItem('token')??''}`},body:JSON.stringify({team_id:team,include_csv:true})});if(!response.ok)throw new Error((await response.json()).detail??'Export failed');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download='audit-export.zip';a.click();URL.revokeObjectURL(url);setSuccess('Signed audit export downloaded.')}catch(e){setError(e instanceof Error?e.message:'Export failed.')}finally{setBusy(false)}};
 return <section><div className="page-heading"><div><span className="eyebrow">Evidence-backed posture</span><h2>Compliance Center</h2><p>Validate controls, export audit evidence, and enforce data boundaries.</p></div></div><nav className="trusted-tabs" aria-label="Compliance sections">{(['overview','audit','policies'] as Tab[]).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);setError('');setSuccess('')}}>{t==='overview'?'Overview':t==='audit'?'Audit exports':'Data policies'}</button>)}</nav>{error&&<p role="alert" className="error-banner">{error}</p>}{success&&<p role="status" className="success-banner">{success}</p>}{tab==='overview'&&<div className="compliance-layout"><div className="control-list">{controls.length?controls.map(c=><article className={`control-card ${c.level}`} key={c.id}><span className="control-icon">{c.level==='pass'?'✓':'!'}</span><div><span className="status-label">{c.level}</span><h3>{c.title}</h3><p>{c.detail}</p><small>Evidence: {c.evidence} · Last checked: {c.last_checked} · Owner: {c.owner}</small></div><button className="secondary" onClick={()=>{window.location.hash=c.target??'settings'}}>{c.remediation}</button></article>):<article className="trusted-panel"><h3>No controls reported</h3><p>Connect a workspace to begin compliance monitoring.</p></article>}</div><aside className="audit-panel"><h3>Audit history</h3>{audit.map(a=><div className="audit-event" key={a.id}><div><strong>{a.event}</strong><small>{a.at}</small></div></div>)}</aside></div>}{tab!=='overview'&&<article className="trusted-panel"><label htmlFor="team-id">Workspace team ID</label><input id="team-id" value={team} onChange={e=>setTeam(e.target.value)} placeholder="team UUID"/>{tab==='audit'?<><span className="eyebrow">Tamper-evident evidence</span><h3>Audit exports</h3><p>Validate the per-team chain and download signed JSONL, manifest, and CSV files.</p><button className="primary" disabled={busy} onClick={()=>void exportAudit()}>{busy?'Building export…':'Validate and export'}</button></>:<><span className="eyebrow">Active policy · version {policy.version}</span><h3>Processing boundaries</h3><label><input type="checkbox" checked={policy.providers.allowed_providers.includes('local')} readOnly/> Local processing</label><label><input type="checkbox" checked={policy.providers.allowed_providers.includes('openai')} readOnly/> OpenAI processing</label><label><input type="checkbox" checked={policy.providers.prohibit_fallback} readOnly/> Prohibit fallback</label><button className="primary" disabled={busy} onClick={()=>void loadPolicy()}>{busy?'Loading…':'Load active policy'}</button></>}</article>}</section>
}
