import type { MeetingCard, WorkspaceView } from './types';

/** Outcome-led home dashboard with first-run and operational affordances. */
export function Dashboard({ navigate, openMeeting }: { navigate: (view: WorkspaceView) => void; openMeeting: (meeting: MeetingCard) => void }) {
  const meeting: MeetingCard = { id: 'q3', title: 'Q3 product roadmap', date: 'Today, 10:30', duration: '42 min', mode: 'General', status: 'needs_review', participants: 6, summary: 'Prioritized activation and enterprise controls.' };
  return <section aria-labelledby="home-title"><div className="hero"><div><span className="eyebrow light">Wednesday, August 5</span><h2 id="home-title">Good evening, Zoltan.</h2><p>Your conversations are turning into clear, accountable work.</p><div className="hero-actions"><button className="hero-primary" onClick={() => navigate('record')}>● Record now</button><button className="hero-secondary" onClick={() => navigate('record')}>↑ Upload audio</button></div></div><div className="hero-visual" aria-hidden="true"><span></span><i></i><b>98%</b><small>time saved</small></div></div>
    <div className="metric-grid"><article><span className="metric-icon purple">✓</span><div><strong>3</strong><small>Awaiting review</small></div><em>Needs you</em></article><article><span className="metric-icon blue">↗</span><div><strong>12</strong><small>Open actions</small></div><em>4 due soon</em></article><article><span className="metric-icon green">◈</span><div><strong>18h</strong><small>Saved this month</small></div><em>↑ 24%</em></article><article><span className="metric-icon amber">✦</span><div><strong>94%</strong><small>Evidence coverage</small></div><em>Excellent</em></article></div>
    <div className="dashboard-grid"><section className="surface"><div className="section-title"><div><span className="eyebrow">Continue where you left off</span><h3>Needs your review</h3></div><button className="text-button" onClick={() => navigate('meetings')}>View all</button></div><button className="review-feature" onClick={() => openMeeting(meeting)}><div className="review-art"><span>▶</span><div className="mini-wave">▂▆▃▇▄▅▂▆▃</div></div><div><span className="status-pill status-needs_review">Needs review</span><h4>Q3 product roadmap</h4><p>3 decisions · 5 actions · 42 min</p><small>Updated 24 minutes ago</small></div><span className="round-arrow">→</span></button></section>
      <section className="surface"><div className="section-title"><div><span className="eyebrow">Today</span><h3>Your actions</h3></div><button className="text-button" onClick={() => navigate('actions')}>Open action center</button></div>{['Review source-linked prototype', 'Share privacy policy draft', 'Confirm onboarding metrics'].map((action, index) => <label className="mini-action" key={action}><input type="checkbox" /><span><strong>{action}</strong><small>{index === 0 ? 'Due today · Q3 roadmap' : index === 1 ? 'Due tomorrow · Security review' : 'Friday · Growth sync'}</small></span></label>)}</section></div>
  </section>;
}
