import { useEffect, useMemo, useState } from 'react';
import { workspaceRequest } from '../api/workspace';
import type { MeetingCard } from './types';

/** Searchable library backed by the canonical persisted meeting endpoint. */
export function MeetingLibrary({ onOpen }: { onOpen: (meeting: MeetingCard) => void }) {
  const [items, setItems] = useState<MeetingCard[]>([]); const [query, setQuery] = useState(''); const [status, setStatus] = useState('all'); const [error, setError] = useState('');
  useEffect(() => { void workspaceRequest<{items: MeetingCard[]}>('/meetings').then((body) => setItems(body.items)).catch((reason: Error) => setError(reason.message)); }, []);
  const visible = useMemo(() => items.filter((item) => item.title.toLowerCase().includes(query.toLowerCase()) && (status === 'all' || item.review_status === status || item.status === status)), [items, query, status]);
  return <section aria-labelledby="meetings-title"><div className="page-heading"><div><span className="eyebrow">Knowledge hub</span><h2 id="meetings-title">Meetings</h2><p>Find every decision, action, and source moment.</p></div><button className="primary">＋ New meeting</button></div>{error && <p role="alert" className="error-banner">{error}</p>}<div className="toolbar" role="search"><label className="search-field"><span aria-hidden="true">⌕</span><input aria-label="Search meetings" placeholder="Search meetings, people, or topics" value={query} onChange={(event) => setQuery(event.target.value)} /></label><select aria-label="Filter meetings by status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="needs_review">Needs review</option><option value="approved">Approved</option></select></div>{visible.length ? <div className="meeting-list">{visible.map((meeting) => <button className="meeting-row" key={meeting.id} onClick={() => onOpen(meeting)}><span className="mode-icon">◉</span><span className="meeting-main"><strong>{meeting.title}</strong><small>{meeting.summary}</small><span className="meta">{meeting.date} · {meeting.duration} · {meeting.participants} people</span></span><span className={`status-pill status-${meeting.review_status ?? meeting.status}`}>{meeting.review_status ?? meeting.status}</span></button>)}</div> : <div className="empty-state"><h3>No meetings match</h3><p>Clear filters or record a conversation.</p></div>}</section>;
}
