import { useEffect, useState } from 'react';
import { workspaceRequest } from '../api/workspace';
import type { MeetingCard, MeetingDetail, MeetingResult } from './types';

function fromUpload(result: MeetingResult): MeetingDetail { const detail = result as MeetingResult & Partial<MeetingDetail>; return { ...result, title: detail.title ?? 'New meeting notes', date: detail.date ?? new Date().toISOString(), duration: detail.duration ?? '', participants: detail.participants ?? 0, review_status: detail.review_status ?? result.review_status, evidence: detail.evidence ?? [], versions: detail.versions ?? [], decisions: detail.decisions ?? result.decisions }; }
/** Persisted evidence-linked review, versioning, approval, and rejection. */
export function ReviewWorkspace({ meeting, result, onBack }: { meeting?: MeetingCard; result?: MeetingResult; onBack: () => void }) {
  const [detail, setDetail] = useState<MeetingDetail | null>(result ? fromUpload(result) : null); const [summary, setSummary] = useState(result?.summary ?? ''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [active, setActive] = useState(0);
  useEffect(() => { if (!meeting) return; void workspaceRequest<MeetingDetail>(`/meetings/${meeting.id}`).then((body) => { setDetail(body); setSummary(body.summary); }).catch((reason: Error) => setError(reason.message)); }, [meeting]);
  const persist = async (status: 'approved' | 'rejected' | 'in_review') => { if (!detail) return; setSaving(true); try { const body = await workspaceRequest<MeetingDetail>(`/meetings/${detail.id}/review`, { method: 'PATCH', body: JSON.stringify({ summary, review_status: status, reviewer: 'Current user' }) }); setDetail(body); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Review could not be saved.'); } finally { setSaving(false); } };
  if (!detail) return <section className="empty-state" aria-live="polite"><h3>Loading meeting evidence…</h3></section>;
  const evidence = detail.evidence[active] ?? { timestamp: 'Not available', speaker: 'Unknown', text: detail.transcript, confidence: 0 };
  return <section className="review-page"><div className="review-topbar"><button className="icon-button" onClick={onBack}>←</button><div><span className="eyebrow">Meeting review</span><h2>{detail.title}</h2></div><span className={`status-pill status-${detail.review_status}`}>{detail.review_status}</span></div>{error && <p role="alert" className="error-banner">{error}</p>}<div className="review-layout"><aside className="review-outline"><h3>Evidence</h3>{detail.evidence.map((item, index) => <button className={index === active ? 'active' : ''} key={item.timestamp} onClick={() => setActive(index)}>{item.timestamp} · {item.speaker}</button>)}<h3>Versions</h3>{detail.versions.map((version) => <small key={version.number}>v{version.number} · {version.reviewer} · {version.status}</small>)}</aside><main className="notes-panel"><div className="audio-player"><audio controls src={detail.audio_url} aria-label="Meeting source audio" /></div><span className="eyebrow">Editable verified record</span><h3>Summary</h3><textarea className="summary-editor" value={summary} onChange={(event) => setSummary(event.target.value)} /><h3>Decisions</h3><ul className="decision-list">{detail.decisions.map((decision, index) => { const text = typeof decision === 'string' ? decision : decision.text; const time = typeof decision === 'string' ? detail.evidence[index]?.timestamp : decision.timestamp; return <li key={text}><span>✓</span><button onClick={() => setActive(Math.min(index, detail.evidence.length - 1))}>{text}<small>Source evidence · {time ?? 'unavailable'}</small></button></li>; })}</ul><div className="wizard-footer"><button className="secondary" disabled={saving} onClick={() => void persist('rejected')}>Reject</button><button className="secondary" disabled={saving} onClick={() => void persist('in_review')}>Save draft</button><button className="primary" disabled={saving} onClick={() => void persist('approved')}>Approve notes</button></div></main><aside className="evidence-panel"><span className="eyebrow">Source evidence</span><h3>{Math.round(evidence.confidence * 100)}% confidence</h3><p>Timestamp {evidence.timestamp}</p><blockquote>{evidence.text}</blockquote><div className="speaker"><span className="avatar">{evidence.speaker[0]}</span><strong>{evidence.speaker}</strong></div></aside></div></section>;
}
