import { useState } from 'react';

/** Safe sharing wizard with audience controls and an exact recipient preview. */
export function SharingCenter() {
  const [step, setStep] = useState(1); const [audience, setAudience] = useState('Selected people'); const [created, setCreated] = useState(''); const [error, setError] = useState('');
  const createShare = async () => { setError(''); try { const response = await fetch('/api/v1/meetings/q3/share', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${sessionStorage.getItem('live_token') ?? ''}` }, body: JSON.stringify({ expires_in: '7d' }) }); if (!response.ok) throw new Error(response.status === 401 ? 'Sign in before creating a secure link.' : 'The link could not be created. Your settings are saved.'); const body = await response.json() as { url: string }; setCreated(body.url); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Sharing failed.'); } };
  return <section aria-labelledby="sharing-title"><div className="page-heading"><div><span className="eyebrow">Controlled distribution</span><h2 id="sharing-title">Safe Sharing</h2><p>Preview exactly what leaves your workspace and revoke access at any time.</p></div><span className="privacy-badge">◈ Policy protected</span></div>
    <div className="share-layout"><aside className="share-steps" aria-label="Sharing steps">{['Audience', 'Content', 'Permissions', 'Protection', 'Recipient preview'].map((label, index) => <button key={label} className={step === index + 1 ? 'active' : step > index + 1 ? 'done' : ''} onClick={() => setStep(index + 1)}><span>{step > index + 1 ? '✓' : index + 1}</span>{label}</button>)}</aside>
      <div className="share-config"><div className="section-title"><div><span className="eyebrow">Step {step} of 5</span><h3>{['Audience', 'Content to share', 'Permissions', 'Protection', 'Recipient preview'][step - 1]}</h3></div></div>
        {step === 1 && <div className="choice-grid">{['Workspace members', 'Selected people', 'External authenticated users', 'Public link'].map((name) => <button key={name} className={audience === name ? 'choice active' : 'choice'} onClick={() => setAudience(name)}><span>{name === 'Public link' ? '◎' : '♙'}</span><strong>{name}</strong><small>{name === 'Public link' ? 'Disabled for Healthcare and Legal meetings' : 'Identity verified before access'}</small></button>)}</div>}
        {step === 2 && <div className="check-list">{['Summary', 'Decisions', 'Actions', 'Transcript', 'Recording', 'Attachments'].map((name, index) => <label key={name}><input type="checkbox" defaultChecked={index < 3} />{name}<small>{index < 3 ? 'Included in the recipient view' : 'Hidden by default'}</small></label>)}</div>}
        {step === 3 && <div className="check-list">{['View', 'Comment', 'Download', 'Copy', 'Reshare'].map((name, index) => <label key={name}><input type="checkbox" defaultChecked={index === 0} />{name}<small>{index === 0 ? 'Required' : 'Optional permission'}</small></label>)}</div>}
        {step === 4 && <div className="protection-grid"><label>Expiration<select><option>7 days</option><option>24 hours</option><option>30 days</option></select></label><label>Passcode<input placeholder="Optional passcode" /></label><label>Domain restriction<input placeholder="example.com" /></label><label>Maximum views<input type="number" min="1" placeholder="Unlimited" /></label><label><input type="checkbox" defaultChecked /> Use redacted version</label><label><input type="checkbox" defaultChecked /> Access notification</label></div>}
        {step === 5 && <div className="recipient-preview"><div className="preview-browser"><div className="preview-bar"><i></i><i></i><i></i><span>Secure meeting recap</span></div><span className="status-pill status-approved">Approved</span><h3>Q3 product roadmap</h3><p className="preview-summary">The team prioritized a unified workspace, source-linked review, and visible privacy controls.</p><h4>Decisions</h4><ul><li>Ship the unified workspace first</li><li>Require review before sensitive sharing</li></ul><h4>Actions</h4><p>3 confirmed actions with owners and deadlines</p></div><div className="preview-note"><strong>This is what recipients will see</strong><p>Audience: {audience}. Transcript and recording remain private unless explicitly enabled.</p></div></div>}
        <div className="wizard-footer"><button className="secondary" disabled={step === 1} onClick={() => setStep(step - 1)}>Back</button>{step < 5 ? <button className="primary" onClick={() => setStep(step + 1)}>Continue</button> : <button className="primary" onClick={() => void createShare()}>Create secure link</button>}</div>{error && <p role="alert" className="error-banner">{error}</p>}{created && <p className="success-banner">Secure link created: {created}</p>}
      </div></div>
  </section>;
}
