import { useRef, useState } from 'react';
import type { MeetingResult } from './types';
import { ProcessingTimeline } from './ProcessingTimeline';
import { workspaceRequest } from '../api/workspace';

/** Real upload-to-review flow backed by POST /api/v1/meetings. */
export function UploadFlow({ onComplete }: { onComplete: (result: MeetingResult) => void }) {
  const [mode, setMode] = useState('general'); const [file, setFile] = useState<File | null>(null); const [consent, setConsent] = useState(false); const [error, setError] = useState(''); const [stage, setStage] = useState(0); const input = useRef<HTMLInputElement>(null);
  const submit = async () => { setError(''); if (!file) { setError('Choose a recording to continue.'); return; } if (file.size === 0) { setError('This recording is empty. Choose another file.'); return; } if (file.size > 25 * 1024 * 1024) { setError('This file is over 25 MB. Compress it or choose a smaller recording.'); return; } if (mode === 'healthcare' && !consent) { setError('Confirm recording consent before processing a Healthcare meeting.'); return; }
    const form = new FormData(); form.set('file', file); form.set('mode', mode); form.set('consent_confirmed', String(consent)); form.set('phi_redaction', String(mode === 'healthcare')); setStage(1);
    try { const response = await fetch('/api/v1/meetings', { method: 'POST', body: form }); setStage(2); const body = await response.json() as MeetingResult & { detail?: string | { message?: string } }; if (!response.ok) throw new Error(typeof body.detail === 'string' ? body.detail : body.detail?.message ?? 'We could not process this recording.'); const saved = await workspaceRequest<MeetingResult>('/meetings', { method: 'POST', body: JSON.stringify({ ...body, title: file.name }) }); setStage(3); onComplete(saved); } catch (reason) { setStage(0); setError(reason instanceof Error ? reason.message : 'Something went wrong. Please retry.'); }
  };
  return <section className="upload-page" aria-labelledby="upload-title"><div className="page-heading centered"><div><span className="eyebrow">Private by design</span><h2 id="upload-title">Turn a conversation into verified work</h2><p>Upload one recording. We will create a reviewable transcript, decisions, and actions.</p></div></div>
    <div className="capture-switch" role="tablist" aria-label="Capture method"><button role="tab" aria-selected="true">↑ Upload</button><button role="tab">● Record live</button><button role="tab">◇ Import calendar</button></div>
    <div className="upload-card"><button className="dropzone" onClick={() => input.current?.click()}><span className="upload-orb">↑</span><strong>{file ? file.name : 'Drop your recording here'}</strong><small>{file ? `${(file.size / 1024 / 1024).toFixed(1)} MB · ready to process` : 'or browse WAV, MP3, MP4, or WebM · up to 25 MB'}</small></button><input ref={input} hidden type="file" accept="audio/wav,audio/mpeg,audio/mp4,audio/webm" onChange={(event) => setFile(event.target.files?.[0] ?? null)} />
      <div className="form-grid"><label>Meeting type<select value={mode} onChange={(event) => { setMode(event.target.value); if (event.target.value !== 'healthcare') setConsent(false); }}><option value="general">General meeting</option><option value="healthcare">Healthcare consultation</option><option value="legal">Legal or deposition</option></select></label><label>Language<select><option>Auto-detect</option><option>English</option><option>Deutsch</option><option>Magyar</option></select></label></div>
      <div className="privacy-settings"><div className="privacy-title"><span>◈</span><div><strong>Privacy settings</strong><small>Visible now, not hidden in settings.</small></div></div><label className="toggle-row"><span><strong>Mask sensitive information</strong><small>{mode === 'healthcare' ? 'Required for Healthcare meetings' : 'Detect and redact PHI before review'}</small></span><input type="checkbox" checked={mode === 'healthcare'} readOnly /></label>{mode === 'healthcare' && <label className="consent-row"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} /><span><strong>Consent confirmed</strong><small>I confirm participants consented to this recording.</small></span></label>}</div>
      {error && <div className="error-banner" role="alert"><span>!</span><div><strong>We need one more thing</strong><p>{error}</p></div></div>}
      {stage > 0 && <ProcessingTimeline active={stage === 1 ? 0 : stage === 2 ? 4 : 7} />}
      <button className="primary full large" onClick={() => void submit()} disabled={stage > 0 && stage < 3}>{stage ? 'Processing…' : 'Create meeting notes'} <span>→</span></button><p className="secure-note">⌁ Encrypted in transit · Never used to train shared models</p>
    </div></section>;
}
